[package]
name = "cop4520-final-rpoject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = "0.9.0"
itertools = "0.10.1"
async-std = "1.10.0"
